[project]
name = "uv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.1",
]

[project.optional-dependencies]
staging = [
    "ruff>=0.6.8",
]
