# This workflow is for code quality checks and tests.
# TIP:  To run GH actions locally, you can use nektos/gh-act:
#           With the GitHub CLI installed, run `gh extension install nektos/gh-act`
#           Then, run `gh act` from the project root. Choose 'medium' image in the first run.
#       You can set an alias to run it from anywhere within the repo:
#           `alias gact='gh act --workflows "$(git rev-parse --show-toplevel)"/.github/workflows'
name: Code Quality

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    setup_uv:
        runs-on: ubuntu-latest
        steps: # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: Install dependencies
              run: uv sync --frozen --dev -p 3.14
              id: uv-sync

    run_tests:
        runs-on: ubuntu-latest
        needs: setup_uv
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: Run tests
              run: uv run pytest ./tests

    ruff:
        runs-on: ubuntu-latest
        needs: setup_uv
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: lint
              run: uv run ruff check ./src ./tests

            - name: format
              run: uv run ruff format --check ./src ./tests

    static_checker:
        runs-on: ubuntu-latest
        needs: setup_uv
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: Set up Python
              run: |
                  uv sync --frozen --dev

            # based on https://github.com/jakebailey/pyright-action/tree/v2/?tab=readme-ov-file#use-with-poetry
            - name: Add the python interpreter to PATH
              run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

            - name: Run static checker
              uses: jakebailey/pyright-action@v2
              # https://github.com/jakebailey/pyright-action
              with:
                  pylance-version: latest-release

    mypy:
        runs-on: ubuntu-latest
        needs: setup_uv
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              # https://github.com/marketplace/actions/astral-sh-setup-uv
              with:
                  version: "latest"

            - name: Runs mypy
              run: uv run mypy ./src
