# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
# Test this workflow with `make gact-release`

name: Upload Python Package

on:
    workflow_dispatch: # Manually trigger the workflow from the Actions tab
    release:
        types: [published]

permissions:
    # 'read' to access the list of commits
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        name: uv-build
        steps:
            # https://github.com/actions/checkout
            - name: Checkout code
              uses: actions/checkout@v4

            # https://github.com/actions/setup-python
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            # https://github.com/astral-sh/setup-uv
            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  # The version of uv to install
                  version: latest # optional, default is latest
                  # The checksum of the uv version to install
                  # checksum: # optional
                  # Used to increase the rate limit when retrieving versions and downloading uv.
                  github-token: ${{ github.token }} # optional, default is ${{ github.token }}
                  # Enable caching of the uv cache
                  enable-cache: false # optional, default is false
                  # Glob pattern to match files relative to the repository root to control the cache.
                  # cache-dependency-glob: # optional, default is **/uv.lock
                  # Suffix for the cache key
                  # cache-suffix: # optional
                  # Local path to store the cache.
                  # cache-local-path: # optional
                  # Custom path to set UV_TOOL_DIR to.
                  # tool-dir: # optional
                  # Custom path to set UV_TOOL_BIN_DIR to.
                  # tool-bin-dir: # optional

            - name: Install dependencies
              run: uv sync --frozen --link-mode=copy

            - name: Build package
              run: uv build --link-mode=copy

            - name: Store artifact
              uses: actions/upload-artifact@main
              with:
                  name: dist
                  path: dist

    deploy:
        runs-on: ubuntu-latest
        name: pypi-deploy
        needs: build
        environment: pypi
        permissions:
            # A 'write' permission is mandatory for trusted publishing
            id-token: write
        steps:
            - name: Download artifact
              uses: actions/download-artifact@main
              with:
                  name: dist
                  path: dist

            - name: Publish package
              # https://github.com/marketplace/actions/pypi-publish
              uses: pypa/gh-action-pypi-publish@release/v1
              # When not using a Trusted Publisher, you can use the following credentials:
              # with:
              #     # https://pypi.org/manage/account/#api-tokens
              #     user: __token__
              #     password: ${{ secrets.PYPI_API_TOKEN }}
